language: cpp
cache: ccache
os: linux

env:
  global:
    - REPO_NAME="node"
    - ARTIFACTS_ROOT_DIR="node_artifacts_dir"
    - ARTIFACTS_DIR=$ARTIFACTS_ROOT_DIR/$REPO_NAME/$TRAVIS_BRANCH/$TRAVIS_JOB_NUMBER

notifications:
  email:
    on_success: always

before_install:
  - curl https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip -o ndk.zip
  - unzip -qq ndk.zip -d $HOME
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r18b
  - |
    case $ARCH in
      arm)
        export TARGET_ARCH="arm"
        ;;
      x86)
        export TARGET_ARCH="x86"
        ;;
      x86_64)
        export TARGET_ARCH="x86_64"
        ;;
      *)
        export TARGET_ARCH="arm64"
        ;;
    esac

install:
  - source ./android-configure $ANDROID_NDK_HOME $TARGET_ARCH
  - make V= -j $(getconf _NPROCESSORS_ONLN)

script: skip

before_deploy:
  - mkdir -p $ARTIFACTS_DIR
  - cp -r out/Release/lib.target $ARTIFACTS_DIR

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_Bucket
  skip_cleanup: true
  local_dir: $ARTIFACTS_ROOT_DIR
  on:
    all_branches: true
